#!/usr/bin/env python3
#-----------------------------------------------------------------------------#
#
# agent_registry.py -- Agent Registry (HTTPS API Server)
#
#   The Agent Registry performs the same structural function for
#   agent service identity that a TLS certificate authority performs for
#   transport identity. TLS certificate authorities are external
#   to OSU: any server operator can obtain a valid TLS certificate.
#   OSU cannot use TLS alone to express agent authorization. The
#   Registry fills this gap. It is the authority OSU controls that
#   decides which agents are authorized, records that decision,
#   and issues short-lived pairing assertions that Chris can verify.
#
#   Two independent authority structures operate in parallel:
#     - TLS certificate authority (external to OSU):
#         asserts "this server controls this domain"
#     - Agent Registry (controlled by OSU):
#         asserts "this agent is authorized by OSU"
#   Chris requires both assertions to proceed.
#
#   This server exposes three endpoints:
#     GET  /agents/{agent_id}    -- look up an agent record
#     POST /pairing/challenge    -- initiate a pairing challenge
#     POST /pairing/verify       -- validate a Trust Badge and
#                                   return a signed assertion
#
#   The Registry stores agent records in a JSON file (agents.json).
#   Challenge tokens are held in memory with a 60-second TTL.
#   Pairing assertions are signed with HMAC-SHA256 using a
#   pre-shared key. Production would use asymmetric signatures
#   so the verification key can be public.
#
# Usage:
#   Started via main.py: python3 main.py serve registry
#
#-----------------------------------------------------------------------------#

import hashlib
import hmac
import json
import logging
import os
import secrets
import sys
import time

from datetime import datetime, timedelta, timezone
from typing import Optional

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

#-----------------------------------------------------------------------------#

logging.basicConfig(level=logging.INFO, stream=sys.stderr)
logger = logging.getLogger(__name__)

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

CHALLENGE_TTL_SECONDS = 60
ASSERTION_TTL_SECONDS = 300

#-----------------------------------------------------------------------------#
#
# load_agents()
#   Read agent records from agents.json. Each record contains the
#   agent's name, endpoint, trust status, and the SHA-256 hash of
#   its Trust Badge. The Registry never stores raw badges.
#
#   Returns:
#       dict: agent_id -> agent record.
#
#-----------------------------------------------------------------------------#

def load_agents() -> dict:
    path = os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "agents.json"
    )
    with open(path, "r") as f:
        return json.load(f)


#-----------------------------------------------------------------------------#
#
# load_signing_key()
#   Read the HMAC signing key from certs/registry_signing.key.
#   This key signs pairing assertions. Chris holds the same key
#   to verify them. This key is unrelated to TLS certificates
#   and unrelated to Trust Badges.
#
#   Demo: Symmetric HMAC key, pre-shared via file. Generated by
#   scripts/mock_ca.py alongside (but independent of) TLS certs.
#
#   Production: Replaced by an asymmetric key pair (RS256 or
#   Ed25519). The Registry holds the private signing key; Chris
#   holds the public verification key.
#
#   Returns:
#       str: The hex-encoded signing key.
#
#-----------------------------------------------------------------------------#

def load_signing_key() -> str:
    path = os.environ.get(
        "REGISTRY_SIGNING_KEY_PATH",
        os.path.join(REPO_ROOT, "certs", "registry_signing.key"),
    )
    with open(path, "r") as f:
        return f.read().strip()


#-----------------------------------------------------------------------------#
#
# sign_assertion()
#   Produce an HMAC-SHA256 signature over the pairing assertion
#   payload. The signature covers agent_id + issued_at + expires_at
#   concatenated with pipe delimiters. The delimiter prevents
#   ambiguity if field values contain substrings of each other.
#
#   Args:
#       key (str): Hex-encoded HMAC key.
#       agent_id (str): The agent being vouched for.
#       issued_at (str): ISO 8601 timestamp.
#       expires_at (str): ISO 8601 timestamp.
#
#   Returns:
#       str: Hex-encoded HMAC digest.
#
#-----------------------------------------------------------------------------#

def sign_assertion(
    key: str, agent_id: str, issued_at: str, expires_at: str
) -> str:
    message = f"{agent_id}|{issued_at}|{expires_at}"
    return hmac.new(
        key.encode(), message.encode(), hashlib.sha256
    ).hexdigest()


#-----------------------------------------------------------------------------#

agents = load_agents()
signing_key = load_signing_key()

# In-memory challenge store: token -> {agent_id, expires_at}
_challenges: dict[str, dict] = {}

app = FastAPI(title="OpenBeavs Agent Registry")


#-----------------------------------------------------------------------------#
#
# GET /agents/{agent_id}
#   Return the public portion of an agent record: name, endpoint,
#   and trust status. Does not return the Trust Badge hash. Chris
#   calls this to discover an agent's endpoint and confirm its
#   status before initiating pairing.
#
#-----------------------------------------------------------------------------#

@app.get("/agents/{agent_id}")
def get_agent(agent_id: str) -> dict:
    if agent_id not in agents:
        raise HTTPException(status_code=404, detail="agent not found")

    record = agents[agent_id]
    return {
        "agent_id": agent_id,
        "name": record["name"],
        "endpoint": record["endpoint"],
        "status": record["status"],
    }


#-----------------------------------------------------------------------------#
#
# POST /pairing/challenge
#   Chris calls this to start the pairing handshake. The Registry
#   generates a random challenge token, stores it with a 60-second
#   TTL, and returns it. Chris forwards the token to Cyrano, who
#   must present it (along with its Trust Badge) to /pairing/verify.
#
#   The challenge token is single-use conceptually: once consumed
#   by /pairing/verify, it is deleted. The TTL is a safety net
#   for tokens that are never consumed.
#
#-----------------------------------------------------------------------------#

class ChallengeRequest(BaseModel):
    agent_id: str


@app.post("/pairing/challenge")
def create_challenge(req: ChallengeRequest) -> dict:
    if req.agent_id not in agents:
        raise HTTPException(status_code=404, detail="agent not found")

    token = secrets.token_hex(32)
    _challenges[token] = {
        "agent_id": req.agent_id,
        "expires_at": time.time() + CHALLENGE_TTL_SECONDS,
    }

    _purge_expired_challenges()

    return {"challenge_token": token}


#-----------------------------------------------------------------------------#
#
# POST /pairing/verify
#   Cyrano calls this to prove its identity. Cyrano presents its
#   agent_id, the challenge token (received from Chris), and its
#   raw Trust Badge. The Registry validates:
#
#     1. The challenge token exists and has not expired.
#     2. The challenge token was issued for this agent_id.
#     3. The SHA-256 hash of the presented Trust Badge matches the
#        stored hash in the agent record.
#     4. The agent's status is approved or provisional.
#
#   If all checks pass, the Registry signs a pairing assertion
#   and returns it. Cyrano relays the assertion to Chris.
#
#   The Trust Badge is a shared secret between the agent and the
#   Registry. It is unrelated to TLS certificates. In the demo,
#   scripts/mock_ca.py generates it; in production, an OSU
#   administrative process provisions it when an agent is
#   registered.
#
#   The challenge token is consumed (deleted) after verification,
#   regardless of success or failure, to prevent replay.
#
#-----------------------------------------------------------------------------#

class VerifyRequest(BaseModel):
    agent_id: str
    challenge_token: str
    trust_badge: str


@app.post("/pairing/verify")
def verify_pairing(req: VerifyRequest) -> dict:
    challenge = _challenges.pop(req.challenge_token, None)

    if challenge is None:
        logger.warning(
            "pairing verify: unknown challenge token for agent %s",
            req.agent_id,
        )
        raise HTTPException(
            status_code=400, detail="invalid challenge token"
        )

    if time.time() > challenge["expires_at"]:
        logger.warning(
            "pairing verify: expired challenge token for agent %s",
            req.agent_id,
        )
        raise HTTPException(
            status_code=400, detail="challenge token expired"
        )

    if challenge["agent_id"] != req.agent_id:
        logger.warning(
            "pairing verify: agent_id mismatch: challenge for %s, "
            "request from %s",
            challenge["agent_id"],
            req.agent_id,
        )
        raise HTTPException(
            status_code=400, detail="agent_id mismatch"
        )

    if req.agent_id not in agents:
        raise HTTPException(
            status_code=404, detail="agent not found"
        )

    record = agents[req.agent_id]

    presented_hash = hashlib.sha256(
        req.trust_badge.encode()
    ).hexdigest()
    if not hmac.compare_digest(
        presented_hash, record["trust_badge_hash"]
    ):
        logger.warning(
            "pairing verify: Trust Badge mismatch for agent %s",
            req.agent_id,
        )
        raise HTTPException(
            status_code=403, detail="Trust Badge mismatch"
        )

    if record["status"] not in ("approved", "provisional"):
        logger.warning(
            "pairing verify: agent %s status is %s",
            req.agent_id,
            record["status"],
        )
        raise HTTPException(
            status_code=403,
            detail=f"agent status is {record['status']}",
        )

    now = datetime.now(timezone.utc)
    issued_at = now.isoformat()
    expires_at = (
        now + timedelta(seconds=ASSERTION_TTL_SECONDS)
    ).isoformat()

    signature = sign_assertion(
        signing_key, req.agent_id, issued_at, expires_at
    )

    logger.info(
        "pairing verify: issued assertion for agent %s", req.agent_id
    )

    return {
        "agent_id": req.agent_id,
        "issued_at": issued_at,
        "expires_at": expires_at,
        "signature": signature,
    }


#-----------------------------------------------------------------------------#
#
# _purge_expired_challenges()
#   Housekeeping. Remove challenge tokens that have passed their
#   TTL. Called opportunistically during challenge creation to
#   prevent unbounded growth of the in-memory store.
#
#-----------------------------------------------------------------------------#

def _purge_expired_challenges() -> None:
    now = time.time()
    expired = [
        token for token, data in _challenges.items()
        if now > data["expires_at"]
    ]
    for token in expired:
        del _challenges[token]


#-----------------------------------------------------------------------------#
#eof#
